### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException length=15; index=15

### ISSUE THREAD

**Issue by yeyintkoko** [negativetwelve/react-native-ux-cam#138]
It is crashing our app in uxcam.jar file in react-native-ux-cam (v5.3.3). Here is the firebase Crashlytics log:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=15; index=15
       at java.util.ArrayList.add(ArrayList.java:468)
       at org.json.JSONArray.put(JSONArray.java:185)
       at com.uxcam.internals.cf.a(:147)
       at com.uxcam.internals.cf.a(:12)
       at com.uxcam.internals.bl.a(:8)
       at com.uxcam.internals.ay$1.onResponse(:300)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

May be you are indexing out of the array's length in the lib somewhere?

`ArrayIndexOutOfBoundsException length=15; index=15`

Could you please fix and update the uxcam RN package asap?
Thanks.

**Comment by yeyintkoko** [comment]
Sorry wrong repo! :)!
