### ISSUE TITLE
React-Native message bridge error throw in Java runtime

### ISSUE THREAD

**Issue by crobinson42** [negativetwelve/react-native-ux-cam#78]
I installed and configured uxcam to work. I tested it for the last 2 weeks fine... now, i'm getting this error when I open my app:

Let me know how I can help debug.

```
2019-02-25 12:12:35.058 16527-17368/com.hhs2 I/MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: -1 bps and the estimated moov size 3195 bytes
2019-02-25 12:12:35.064 16527-17380/com.hhs2 I/MPEG4Writer: setStartTimestampUs: 10472686720
2019-02-25 12:12:35.064 16527-17380/com.hhs2 I/MPEG4Writer: Earliest track starting time: 10472686720
2019-02-25 12:12:35.089 16527-17368/com.hhs2 D/MPEG4Writer: Video track stopping
2019-02-25 12:12:35.089 16527-17368/com.hhs2 D/MPEG4Writer: Video track source stopping
2019-02-25 12:12:35.089 16527-17380/com.hhs2 W/MPEG4Writer: 0-duration samples found: 1
2019-02-25 12:12:35.089 16527-17368/com.hhs2 D/MPEG4Writer: Video track source stopped
2019-02-25 12:12:35.089 16527-17380/com.hhs2 I/MPEG4Writer: Received total/0-length (1/0) buffers and encoded 1 frames. - Video
2019-02-25 12:12:35.090 16527-17368/com.hhs2 D/MPEG4Writer: Video track stopped
2019-02-25 12:12:35.090 16527-17368/com.hhs2 D/MPEG4Writer: Stopping writer thread
2019-02-25 12:12:35.090 16527-17379/com.hhs2 D/MPEG4Writer: 0 chunks are written in the last batch
2019-02-25 12:12:35.090 16527-17368/com.hhs2 D/MPEG4Writer: Writer thread stopped
2019-02-25 12:12:35.090 16527-17368/com.hhs2 D/MPEG4Writer: Video track stopping
2019-02-25 12:12:35.122 16527-17333/com.hhs2 E/unknown:ReactNative: Exception in native call
    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
        at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:134)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
2019-02-25 12:12:35.150 16527-16527/com.hhs2 D/ReactNative: CatalystInstanceImpl.destroy() start
2019-02-25 12:12:35.152 16527-17333/com.hhs2 D/BluetoothSerial: Catalyst instance destroyed
2019-02-25 12:12:35.152 16527-17333/com.hhs2 D/BluetoothSerial: Stop all devices
2019-02-25 12:12:35.156 16527-17332/com.hhs2 W/unknown:ReactNative: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
2019-02-25 12:12:35.157 16527-17332/com.hhs2 W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {e2af06a} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {e2af06a} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.post(Handler.java:338)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:59)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by crobinson42** [comment]
I found the root cause, `RNUxcam.setUserProperty('siteNumber', 15)` where the arguments aren't coerced.
